### PR TITLE
Created Result#to_hash

### PR DESCRIPTION
**Pull request by tinogomes**

### CODE REVIEW

**Comment by yhirose** [comment]
@tinogomes, thanks for the contribution.

**Comment by tinogomes** [comment]
@yhirose I thank you for this gem. Do you know when you will publish a new version with this feature?

**Comment by yhirose** [comment]
I have just bumped up the version number to 0.1.7. Please check if it works on your system.

**Comment by tinogomes** [comment]
Thank you again!

**Pull request merged**
